app_article_homepage:
    path:     /homepage
    defaults: { _controller: AppBundle:Article:homepage }


app_article_creation:
    path:     /new
    defaults: { _controller: AppBundle:Article:new }


app_article_creating:
    path:     /create
    defaults: { _controller: AppBundle:Article:create }

app_article_show:
    path:  /show
    defaults : { _controller: AppBundle:Article:show }